### PR TITLE
Add README Card

### PR DESCRIPTION
**Pull request by ShowMeYourSkil**
Hi Zekro,

With the Readme card I think it looks even nicer.
The theme tokyonight does not look bad in the cards either.

image

image

### CODE REVIEW

**Comment by zekroTJA** [comment]
Oh yeah, thats really nice, thank you. But could you also add the `MyRunes` Project as card? 
image

Also, it would be nice if the cards are also arranged like the other ones above with the same color theme, when this is possible.
image

I've achieved this by placing the images in an `img` HTML tag and wrapped them into a center aligned division.
```html
<div align="center">
<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=zekroTJA&theme=tokyonight&layout=compact&hide=css" height="170" />&nbsp;&nbsp;&nbsp;<img src="https://github-readme-stats.vercel.app/api?username=zekroTJA&theme=tokyonight&show_icons=true" height="170" />
</div>
```

Would be nice if you could change it so that it matches the style of the cards above. No problem if not, then I'll merge the pull request in a new branch and do the changes myself. ^^

**Comment by ShowMeYourSkil** [comment]
Hi, myrunes is an orga and not a repository so I cannot add it as a card. Should I add a specific repo for myrunes?

**Comment by ShowMeYourSkil** [comment]
Would you like the cards placed as above? 

image

**Comment by zekroTJA** [comment]
> Hi, myrunes is an orga and not a repository so I cannot add it as a card. Should I add a specific repo for myrunes?

Oh yeah, right, totally forgot that. :D Would be nice if you could pick the [backend repo](https://github.com/myrunes/backend).

> Would you like the cards placed as above?

Yes, in two columns. ^^ You can play with the `width` and `height` attributes of the image tag to adjust the sizes. No problem if it's not perfect, I can try to adjust and optimize it myself. ^^

**Review by ShowMeYourSkil — COMMENTED** [review]
* Update README Card

**Comment by ShowMeYourSkil** [comment]
- I have now implemented myrunes backend and adapted the new style.

image

**Comment by zekroTJA** [comment]
Thank you very much. Looks beautiful 👌

**Pull request merged**
